### ISSUE TITLE
Include HA terms and acronyms

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-documentation-dicts#2]
Here is a small list found by spellchecking of our HA guides. Maybe you would like to add that to our dictionary.

## Acronyms

```
ASR
BBU
CTDB
DCs
GFS2
KTCPVS
LVs
RRP
TDB
VGs, VM's
```

## Terms

```
bindnetaddr
colocated
conntrackd
crony
failback
kdump
locational (constraints)
lvmlockd
mcastaddr
o2cb
pcmk
promotable
protectees
topologies
tunable
sublevel
splitted
switchover
unclustered
```

## Names and Products

```
DataProtector
NetBackup
NetWorker
QNetix
Symantec
Tivoli
```

**Comment by sknorr** [comment]
I have added most of these, but not all -- I excluded:

- tunable, as we have "tuneable" already
- protectees, because it sounded wrong and the context it appeared in did not make it sound like that was established terminology
- splitted, because the correct past of "split" is also "split"
- crony was misspelled, so I added Chrony
- QNetix is a misspelling as well, I added Qnetix
