### ISSUE TITLE
Add new terms

### ISSUE THREAD

**Issue by tomschr** [openSUSE/suse-documentation-dicts#4]
Maybe possible additions to the list:

```
bugfix +es +ing
bootloader +s
re-create +s +ing +d
roundrobin
```

**Comment by sknorr** [comment]
None of them are all that good, you should instead replace by:

* "bug fixes"
* "boot loader" (cf. https://github.com/SUSE/doc-styleguide/blob/develop/xml/docu_styleguide.terminology.xml#L170)
* "create (again)" - even if there is a dash in "re-create", it is still awfully close to "recreate"
* "round-robin"

I will add "re-create" because it is mentioned in the style guide (still a terrible word).
