### ISSUE TITLE
A List of Unknown Words from the Deployment Guide

### ISSUE THREAD

**Issue by taroth21** [openSUSE/suse-documentation-dicts#6]
- [x] Gibibyte
- [x] rewritable
- [x] NGINX
- [x] kISO
- [x] Netinstall? (ISO)
- [x] realtime
- [x] minidisk
- [x] minidisks
- [ ] ~~Minidisk~~
- [x] Flatpak
- [x] multiversion

**Comment by sknorr** [comment]
Added some items that should be uncontroversial:
* the following: "gibibyte" (and similar, like kibibyte etc.) -- note lowercase spelling!
* "Nginx" -- note that only first characters is capitalized (not an acronym, just a shorter version of "Engine X")
* minidisk(s) - IBM term, not lowercase spelling. Uppercase should be rejected.
* "Flatpak"

**Comment by lproven** [comment]
On 11/05/2020 17:53, Tanja Roth wrote:
> Gibibyte

Legitimate, but only capitalised at the beginning of a sentence, which 
should be rare but is conceivable.

"Gibibyte is the binary equivalent of gigabyte," for example.

> rewritable

I think that's acceptable.

> NGINX

As per SK's comment.

> kISO

Not a word, AFAIK.

> Netinstall? (ISO)

Is used for Ubuntu, Mageia etc. E.g.
https://askubuntu.com/questions/566958/what-is-the-meaning-of-minimal-netinstall-and-bin-iso

This page (which I have just updated, it was riddled with typos) 
suggests this is *not* the name used by openSUSE:
https://en.opensuse.org/SDB:Network_installation


> realtime

Commonly used, IMHO, but "real-time" would also be acceptable.

> minidisk
> minidisks
> Minidisk

Terms used in IBM mainframe stuff. Caps permissible at beginning of 
sentence.

> DirMaint

IBM tool:
https://www.ibm.com/support/knowledgecenter/en/SSB27U_6.4.0/com.ibm.zvm.v640.hcpk3/conde.htm

> linux

Permissible if talking about kernel package names, I suppose, but 
otherwise should be capitalized.

> minidisk
> Minidisk
> minidisks

See earlier: fine.

> multiversion
> Multiversion

I'd probably favour "multi-version" but I think it's acceptable.

> Flatpak

Is a trademark for GNOME/Red Hat containerized software packages:
https://flatpak.org/

-- 
Liam Proven - Technical Writer, SUSE Linux s.r.o.
Corso II, Křižíkova 148/34, 186-00 Praha 8 - Karlín, Czechia
Email: lproven@suse.com - Office telephone: +420 284 241 084

**Comment by sknorr** [comment]
@lproven, could you clean up above comment? Some of what you say duplicates my comment and is done already, some of it is repeated in your own mail.

**Comment by sknorr** [comment]
@lproven Spellcheckers (at least aspell and hunspell) automatically assume that words that are lowercased in their dictionaries can also be used either with an uppercase first letter or all-uppercase. As such, there is no need to add "Gibibyte" in addition to "gibibyte" or "Minidisk" in addition to "minidisk", both of which I'd already added before your comment.

**Comment by dariavladykina** [comment]
All terms have been added to the new wordlist.
